# Generated by Django 4.0.5 on 2022-07-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branch',
            table='branches',
        ),
    ]
