# Generated by Django 4.0.5 on 2022-07-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_alter_branch_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
