# Generated by Django 4.0.5 on 2022-07-04 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimate',
            old_name='electric_folding_mirrort',
            new_name='electric_folding_mirror',
        ),
        migrations.RenameField(
            model_name='insurancehistory',
            old_name='hsitory',
            new_name='history',
        ),
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='hsitory',
            new_name='history',
        ),
    ]
